

name: minerva_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - boto3
  - langchain
  - langgraph
  - pytest

  - pip:
    - black[jupyter]
    - langchain-aws
    - langchain-openai
    - langchain-community
    - llama_cpp_python
